image: node:16.13

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

pages:
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
  stage: deploy
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build
    - npm install -g wrangler --unsafe-perm=true
    - npx wrangler pages publish ./build --project-name=nftao
  artifacts:
    paths:
      - public
  only:
    - main